import os

POSTGRES_DB = os.environ.get('POSTGRES_DB')

CORS_ALLOWED = os.environ.get('CORS_ALLOWED')

DAILY_CRON_HOUR = os.environ.get('DAILY_CRON_HOUR')
DAILY_CRON_MINUTE = os.environ.get('DAILY_CRON_MINUTE')

WEEKLY_CRON_DAY_OF_WEEK = os.environ.get('WEEKLY_CRON_DAY_OF_WEEK')
WEEKLY_CRON_HOURS = os.environ.get('WEEKLY_CRON_HOURS')
WEEKLY_CRON_MINUTES = os.environ.get('WEEKLY_CRON_MINUTES')

MONTHLY_CRON_DAY = os.environ.get('MONTHLY_CRON_DAY')
MONTHLY_CRON_HOURS = os.environ.get('MONTHLY_CRON_HOURS')
MONTHLY_CRON_MINUTES = os.environ.get('MONTHLY_CRON_MINUTES')

YEARLY_CRON_MONTH = os.environ.get('YEARLY_CRON_MONTH')
YEARLY_CRON_DAY = os.environ.get('YEARLY_CRON_DAY')
YEARLY_CRON_HOURS = os.environ.get('YEARLY_CRON_HOURS')
YEARLY_CRON_MINUTES = os.environ.get('YEARLY_CRON_MINUTES')
